### ISSUE TITLE
NDVI MAX, does it work?

### ISSUE THREAD

**Issue by makovz** [sentinel-hub/custom-scripts#133]
https://custom-scripts.sentinel-hub.com/sentinel-2/max_ndvi/
It seems not working, anyone has ever tried it? thanks

**Comment by gmilcinski** [comment]
Sure, it is working.
Did you turn on temporal processing? E.g. adding TEMPORAL=true to the WCS call, or setting it in the advanced parameters?

See example [here](https://apps.sentinel-hub.com/sentinel-playground-temporal/?source=S2&lat=51.50722&lng=-0.12750000000005457&zoom=12&preset=CUSTOM&layers=B01,B02,B03&maxcc=20&gain=1.0&gamma=1.0&time=2015-01-01%7C2020-03-08&atmFilter=&showDates=false&evalscript=Ly9CYXNpYyBpbml0aWFsaXphdGlvbiBzZXR1cCBmdW5jdGlvbgpmdW5jdGlvbiAgICBzZXR1cCAoZHNzKSB7Ci8vTGlzdCBvZiBhbGwgYmFuZHMsIHRoYXQgd2lsbCBiZSB1c2VkIGluIHRoZSBzY3JpcHQsIGVpdGhlciBmb3IgdmlzdWFsaXphdGlvbiBvciBmb3IgY2hvb3NpbmcgYmVzdCBwaXhlbAogIHNldElucHV0Q29tcG9uZW50cyhbZHNzLkIwNCxkc3MuQjA4XSk7Ci8vVGhpcyBjYW4gYWx3YXlzIGJlIHRoZSBzYW1lIGlmIG9uZSBpcyBkb2luZyBSR0IgaW1hZ2VzCiAgc2V0T3V0cHV0Q29tcG9uZW50Q291bnQoMyk7Cn0KCi8qCkluIHRoaXMgZnVuY3Rpb24gd2UgbGltaXQgdGhlIHNjZW5lcywgd2hpY2ggYXJlIHVzZWQgZm9yIHByb2Nlc3NpbmcuIApUaGVzZSBhcmUgYmFzZWQgYWxzbyBvbiBpbnB1dCB2YXJpYWJsZXMsIGNvbWluZyBmcm9tIFBsYXlncm91bmQuIApFLmcuIGlmIG9uZSBzZXRzIGRhdGUgIjIwMTctMDMtMDEiICgiVE8gZGF0ZSIpIGFuZCBjbG91ZCBjb3ZlcmFnZSBmaWx0ZXIgMzAlLCAKYWxsIHNjZW5lcyBvbGRlciB0aGFuIDIwMTctMDMtMDEgd2l0aCBjbG91ZCBjb3ZlcmFnZSAzMCUgd2lsbCBiZSBjaGVja2VkIGFnYWluc3QKZnVydGhlciBjb25kaXRpb25zIGluIHRoaXMgZnVuY3Rpb24uClRoZSBtb3JlIHNjZW5lcyB0aGVyZSBhcmUsIGxvbmdlciBpdCB3aWxsIHRha2UgdG8gcHJvY2VzcyB0aGUgZGF0YS4KQWZ0ZXIgNjAgc2Vjb25kcyBvZiBwcm9jZXNzaW5nLCB0aGVyZSB3aWxsIGJlIGEgdGltZW91dC4KKi8KCmZ1bmN0aW9uIGZpbHRlclNjZW5lcyAoc2NlbmVzLCBpbnB1dE1ldGFkYXRhKSB7CiAgICByZXR1cm4gc2NlbmVzLmZpbHRlcihmdW5jdGlvbiAoc2NlbmUpIHsKLy9IZXJlIHdlIGxpbWl0IGRhdGEgYmV0d2VlbiAiKFRPIGRhdGUgLSAxIG1vbnRoKSB0byAoVE8gZGF0ZSkKCSAgcmV0dXJuIHNjZW5lLmRhdGUuZ2V0VGltZSgpPj0oaW5wdXRNZXRhZGF0YS50by5nZXRUaW1lKCktMSozMSoyNCozNjAwKjEwMDApIDsKICAgIH0pOwp9CgpmdW5jdGlvbiBjYWxjTkRWSShzYW1wbGUpIHsKICB2YXIgZGVub20gPSBzYW1wbGUuQjA0K3NhbXBsZS5CMDg7CiAgcmV0dXJuICgoZGVub20hPTApID8gKHNhbXBsZS5CMDgtc2FtcGxlLkIwNCkgLyBkZW5vbSA6IDAuMCk7Cn0KZnVuY3Rpb24gZXZhbHVhdGVQaXhlbChzYW1wbGVzKSB7ICAKICB2YXIgbWF4ID0gMDsKICBmb3IgKHZhciBpPTA7aTxzYW1wbGVzLmxlbmd0aDtpKyspIHsKICAgICAgdmFyIG5kdmkgPSBjYWxjTkRWSShzYW1wbGVzW2ldKTsKICAgIG1heCA9IG5kdmkgPiBtYXggPyBuZHZpOm1heDsKICB9CmlmIChtYXg8LTEuMSkgcmV0dXJuIFswLDAsMF07CmVsc2UgaWYgKG1heDwtMC4yKSByZXR1cm4gWzAuNzUsMC43NSwwLjc1XTsKZWxzZSBpZiAobWF4PC0wLjEpIHJldHVybiBbMC44NiwwLjg2LDAuODZdOwplbHNlIGlmIChtYXg8MCkgcmV0dXJuIFsxLDEsMC44OF07CmVsc2UgaWYgKG1heDwwLjAyNSkgcmV0dXJuIFsxLDAuOTgsMC44XTsKZWxzZSBpZiAobWF4PDAuMDUpIHJldHVybiBbMC45MywwLjkxLDAuNzFdOwplbHNlIGlmIChtYXg8MC4wNzUpIHJldHVybiBbMC44NywwLjg1LDAuNjFdOwplbHNlIGlmIChtYXg8MC4xKSByZXR1cm4gWzAuOCwwLjc4LDAuNTFdOwplbHNlIGlmIChtYXg8MC4xMjUpIHJldHVybiBbMC43NCwwLjcyLDAuNDJdOwplbHNlIGlmIChtYXg8MC4xNSkgcmV0dXJuIFswLjY5LDAuNzYsMC4zOF07CmVsc2UgaWYgKG1heDwwLjE3NSkgcmV0dXJuIFswLjY0LDAuOCwwLjM1XTsKZWxzZSBpZiAobWF4PDAuMikgcmV0dXJuIFswLjU3LDAuNzUsMC4zMl07CmVsc2UgaWYgKG1heDwwLjI1KSByZXR1cm4gWzAuNSwwLjcsMC4yOF07CmVsc2UgaWYgKG1heDwwLjMpIHJldHVybiBbMC40NCwwLjY0LDAuMjVdOwplbHNlIGlmIChtYXg8MC4zNSkgcmV0dXJuIFswLjM4LDAuNTksMC4yMV07CmVsc2UgaWYgKG1heDwwLjQpIHJldHVybiBbMC4zMSwwLjU0LDAuMThdOwplbHNlIGlmIChtYXg8MC40NSkgcmV0dXJuIF.swLjI1LDAuNDksMC4xNF07CmVsc2UgaWYgKG1heDwwLjUpIHJldHVybiBbMC4xOSwwLjQzLDAuMTFdOwplbHNlIGlmIChtYXg8MC41NSkgcmV0dXJuIFswLjEzLDAuMzgsMC4wN107CmVsc2UgaWYgKG1heDwwLjYpIHJldHVybiBbMC4wNiwwLjMzLDAuMDRdOwplbHNlIHJldHVybiBbMCwwLjI3LDBdOwoKfQ%3D%3D&temporal=true)
(in the Effects tab you can turn on and off the temporal state, so that you see the difference

**Comment by makovz** [comment]
Thanks! I didn't know the option "enable temporal data", no indication about it the script page (https://custom-scripts.sentinel-hub.com/sentinel-2/max_ndvi/#) and, in the example from the "Evaluate and visualize" section, this option can't be enabled, so probably it returns the image of the last available date. Anyway, that's OK. From WMS/WCS call, how can I set a defined time interval? Thanks a lot

**Comment by gmilcinski** [comment]
You are right, I added the note and corrected the link in Evaluate section.  
In WCS/WMS you can use the [TIME](https://www.sentinel-hub.com/develop/documentation/api/ogc_api/wcs-request) parameter, which will define the high-level temporal period. Furthermore, there is "filterScenes" function in the script itself, which is currently limiting execution to 1 month. You can adjust this in line with your needs (longer period will take longer to process).

**Comment by makovz** [comment]
thanks a lot
