### ISSUE TITLE
B12 of Observation outlier detector 

### ISSUE THREAD

**Issue by tommy0827** [sentinel-hub/custom-scripts#191]
Frist, Than you so much for sharing your great script. 

I have a question about Observation outlier detector.
Line 22 of script is below

let shadow = predict(sample.B01, sample.B02, sample.B03, sample.B04, sample.B05, sample.B06, sample.B07, sample.B08, sample.B08A, sample.B09, sample.B10, sample.B11, sample.B11, NDVI, NBSI) > 0.5

Why do you use two B11? Should it be B12?

**Comment by mlubej** [comment]
Hi @tommy0827 !

Good observation skills! We only noticed this ourselves a short while ago but hadn't managed to fix it yet.

> Why do you use two B11? Should it be B12?

It should definitely be B12.

Also, there is an additional mistake in the same line, with `B08A`, instead of `B8A`. I've pushed a fix so this should be taken care of.

Additionally, you might want to experiment with a lower (more inclusive) threshold for the shadows (down to 0.2 or something). We noticed it performs better, but it could just be one use particular use-case. Just don't take it for granted in case you think it's optimal :)

Thanks again!

Cheers,
Matic
