### ISSUE TITLE
Add NDWI?

### ISSUE THREAD

**Issue by CTO22** [sentinel-hub/custom-scripts#6]
and NDWI secript for sentinel2 is available:

https://www.sentinel-hub.com/eoproducts/ndwi-normalized-difference-water-index

any chance this can be added to the index list?

**Comment by gmilcinski** [comment]
You can find NDWI (and many other scripts) in the Custom scripts repository:  
https://github.com/sentinel-hub/custom-scripts/  

NDWI specifically here:  
https://github.com/sentinel-hub/custom-scripts/blob/master/sentinel-2/ndwi/script.js  

As you are probably interested in the values, rather than the visualization, you can use   
`return [ndwi];  `
instead of  
`return colorBlend(). `
